[package]
name = "recollection"
version = "0.1.0"
edition = "2018"
description = "implementations and reimplementations of common data structures and algorithms"
keywords = ["algorithms"]
license = "MIT"
homepage = "https://clp.is/projects/recollection"
documentation  = "https://clp.is/projects/recollection"
readme = "https://clp.is/projects/recollection"

[lib]
name = "recollection"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[features]
default = ["graph", "chain"]
graph = []
chain = []

[[test]]
name = "graph"
path = "tests/data/graph.rs"


[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
